# frozen_string_literal: true
source 'https://rubygems.org'
gem 'builder', '~> 3.0'
gem 'kramdown', '~> 1.0'
gem 'middleman', '~> 4.0'
gem 'middleman-blog', '~> 4.0'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-livereload', '~> 3.0'
gem 'nokogiri', '~> 1.0'
gem 'opal', '~> 0.10.0'
