# frozen_string_literal: true
source 'https://rubygems.org'
gem 'builder'
gem 'kramdown'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-deploy', '>= 2.0.0.pre.alpha'
gem 'middleman-livereload'
gem 'nokogiri'
gem 'opal'
