name: Build and Deploy
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
          bundler-cache: true
      - run: bundle install --jobs 4 --retry 3
      - name: checkout build
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PAT }}
          ref: master
          path: build
      - name: build and deploy
        run: |
          bundle config --local path vendor/bundle
          bundle exec middleman build
          cd build
          git config user.email "tonytonyjan@gmail.com"
          git config user.name "Jian Weihang"
          git add -A
          git commit -m "$(date)"
          git push
