name: Build and Deploy
on:
  push:
    branches:
      - source
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        id: cache
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-
      - name: bundle install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          bundle install --jobs 4 --retry 3 --path vendor/bundle
          - name: Install Dependencies
      - name: checkout build
        uses: actions/checkout@v2
        with:
          ref: master
          path: build
      - name: build
        run: |
          bundle exec middleman build
          cd build
          git add -A
          git commit -m "$(date)"
          git push
